// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tjhqerfowkqcxttddzfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRqaHFlcmZvd2txY3h0dGRkemZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNTIwMTQsImV4cCI6MjA2OTYyODAxNH0.Y3BqxrIXUUNflQ1-er0Z5WVXe365E_foQ3m7gOMv2Do";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
