// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htafaqzewyqgfttthfcz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0YWZhcXpld3lxZ2Z0dHRoZmN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3OTMxNzAsImV4cCI6MjA2OTM2OTE3MH0.REQbDRUlFDiP68rW0x7SuBapjVF_nHMewjrLxxfCRLo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});